accounts/urls.py
from django.urls import path
from .views import profile, profile_edit, signup


app_name = 'accounts'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('profile/', profile, name='profile'),
    path('profile/edit/', profile_edit, name='profile_edit'),
]

lib/urls.py
from django.urls import path
from . import views


app_name = 'lib'


urlpatterns = [
    path('', views.BookList.as_view(), name='book_list'),
    path('<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
    path('add/', views.add_book, name='add_book'),
    path('<book_id>/edit/', views.edit_book, name='edit_book'),
    path('<book_id>/delete/', views.delete_book, name='delete_book'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),

    path('', include('lib.urls', namespace='lib')),
    path('borrowing/', include('borrowing.urls', namespace='borrowing')),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.


class Profile(models.Model):
    user = models.ForeignKey(
        User, related_name='user_profile', on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=16, blank=True, null=True)
    address = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return str(self.user)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

accounts/forms.py
from django import forms
from . models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['phone_number', 'address']

accounts/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import Profile
from .forms import UserForm, ProfileForm, UserCreateForm
from django.urls import reverse
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.decorators import login_required


def signup(request):
    if request.method == 'POST':
        signup_form = UserCreateForm(request.POST)
        if signup_form.is_valid():
            signup_form.save()
            # return redirect(reverse('login'))
            username = signup_form.cleaned_data['username']
            password = signup_form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect(reverse('accounts:profile'))

    else:
        signup_form = UserCreateForm()

    return render(request, 'registration/signup.html', {'signup_form': signup_form})


@login_required
def profile(request):
    profile = Profile.objects.get(user=request.user)
    return render(request, 'profile/profile.html', {'profile': profile})


@login_required
def profile_edit(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(
            request.POST, request.FILES, instance=profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            my_form = profile_form.save(commit=False)
            my_form.user = request.user
            my_form.save()
            messages.success(request, 'Profile details updated.')
            return redirect(reverse('accounts:profile'))

    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=profile)

    return render(request, 'profile/profile_edit.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

accounts/templates/profile/profile.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<style>
	.col-md-6
	{
		color:rgb(0, 0, 0);
		background-color: rgb(226, 226, 226,.7);
	}
	.btn
	{
		margin-left: 20px;
		border-radius: 5%;
	}
	</style>
<div class="row">
	<div class="col-md-6 mx-auto mt-5 mb-5 text-center">
		<h1>
			Username: {{profile.user.username}}
		</h1>
		<h2 >
			Email Addreess: {{profile.user.email}}
		</h2>
		<h3 >
			Phone Number: {{profile.phone_number}}
		</h3>
		<h3 >
			Address: {{profile.address}}
		</h3>
<br><br>

		<a href="{% url 'accounts:profile_edit' %}" class="btn" style="background-color: rgb(253, 190, 31);">Edit Profile</a>
		<a href="{% url 'password_change' %}" class="btn" style="background-color: rgb(53, 156, 216);">Change Password</a>
	</div>
</div>



{% endblock content %}

accounts/templates/profile/profile_edit.html
{% extends 'base.html' %}

{% load static %}

{% load bootstrap4 %}
{% block content %}
<style>
    .row
    {
        background-color: rgba(0, 0, 0, 0.7);
	  color:rgb(255, 255, 255);
    }
    </style>
<div class="row">
	<div class="col-md-4 mx-auto mt-5 mb-5">
		<form action="" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{% bootstrap_form user_form %}
			{% bootstrap_form profile_form %}

			<div class="d-grid gap-2 my-3">
				<input type="submit" value="edit profile" class="btn btn-success">
			</div>
		</form>
	</div>
</div>
{% endblock content %}