borrowing/urls.py
from django.urls import path
from . import views


app_name = 'borrowing'


urlpatterns = [
    path('', views.borrowing_list, name='borrowing_list'),
    path('add/', views.add_borrow, name='add_borrow'),
    path('<borrow_id>/', views.borrowing_detail, name='borrowing_detail'),
    path('<borrow_id>/edit/', views.edit_borrow, name='edit_borrow'),
    path('<borrow_id>/delete/', views.delete_borrow, name='delete_borrow'),
]

lib/urls.py
from django.urls import path
from . import views


app_name = 'lib'


urlpatterns = [
    path('', views.BookList.as_view(), name='book_list'),
    path('<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
    path('add/', views.add_book, name='add_book'),
    path('<book_id>/edit/', views.edit_book, name='edit_book'),
    path('<book_id>/delete/', views.delete_book, name='delete_book'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),

    path('', include('lib.urls', namespace='lib')),
    path('borrowing/', include('borrowing.urls', namespace='borrowing')),

]

borrowing/models.py
from django.db import models
from django.contrib.auth import get_user_model
from lib.models import Book

User = get_user_model()


class Borrow(models.Model):
    user = models.ForeignKey(
        User, related_name='borrow', on_delete=models.CASCADE)
    book = models.ForeignKey(
        Book, related_name='borrow', on_delete=models.CASCADE)
    exp = models.DateField()

    def __str__(self):
        return f"{self.user} - {self.book}"

borrowing/forms.py
from django import forms
from .models import Borrow


class BorrowForm(forms.ModelForm):
    class Meta:
        model = Borrow
        fields = ["book", 'exp']

borrowing/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Borrow
from .forms import BorrowForm
from django.contrib.auth.decorators import login_required


@login_required
def borrowing_list(request):
    borrow = Borrow.objects.filter(user=request.user)
    context = {
        'borrow': borrow,
    }
    return render(request, 'borrowing/book_list.html', context)


@login_required
def borrowing_detail(request, borrow_id):
    borrow = get_object_or_404(Borrow, pk=borrow_id)
    context = {
        'borrow': borrow,
    }
    return render(request, 'borrowing/book_detail.html', context)


@login_required
def add_borrow(request):
    user = request.user
    if request.method == 'POST':
        form = BorrowForm(request.POST)
        if form.is_valid():
            borrow = form.save(commit=False)
            borrow.user = user
            borrow.save()
            return redirect("borrowing:borrowing_list")
    else:
        form = BorrowForm()

    context = {
        "form": form
    }

    return render(request, 'borrowing/book_add.html', context)


@login_required
def edit_borrow(request, borrow_id):
    bor = get_object_or_404(Borrow, pk=borrow_id)
    user = request.user
    if request.method == 'POST':
        form = BorrowForm(request.POST, instance=bor)
        if form.is_valid():
            borrow = form.save(commit=False)
            borrow.user = user
            borrow.save()
            return redirect("borrowing:borrowing_list")
    else:
        form = BorrowForm(instance=bor)

    context = {
        "form": form
    }

    return render(request, 'borrowing/book_add.html', context)


@login_required
def delete_borrow(request, borrow_id):
    bor = get_object_or_404(Borrow, pk=borrow_id)
    bor.delete()
    return redirect("borrowing:borrowing_list")

templates/borrowing/book_add.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<style>
  .col-md-6
  {
    background-color: rgb(134, 134, 134);
  }
  </style>
<div class="row">
  <div class="col-md-6 mx-auto ">
    <form method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <div class="d-grid gap-2 my-3">
        <input type="submit" value="add / edit borrow" class="btn btn-success">
      </div>
    </form>
  </div>
</div>
{% endblock content %}

templates/borrowing/book_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    .s
    {
        background-color: rgba(73, 73, 73, 0.88);
    }
    .h
    {
        color:cornsilk;
    }
    </style>
<div class="s">
<h1 class="h">Borrower: {{borrow.user}}</h1>
<h2 class="h">Book: {{borrow.book}}</h2>
<p class="h">Expired Date: {{borrow.exp}}</p>
<a href="{% url 'borrowing:edit_borrow' borrow.id %}" style="background-color: rgb(228, 187, 5); color:black" class="btn ">edit</a>
<a href="{% url 'borrowing:delete_borrow' borrow.id %}" style="background-color: rgb(211, 14, 8); color:black" class="btn ">return</a>
</div>
{% endblock content %}

templates/borrowing/book_list.html
{% extends 'base.html' %}

{% block content %}
<style>
  .d
  {
    background-color: rgb(71, 71, 71);
  }
  .go
  {
    background-color: rgb(0, 0, 0);
    width: 90px;
    border-radius: 8%;
    color: cornsilk;
  }
  </style>
<form  class="d" method="POST">
  {% csrf_token %}
  <label style="color :bisque">search</label>
  <input type="search" name="search">
  <select name="select" id="se" >
    <option value="name">name</option>
    <option value="isbn">isbn</option>
    <option value="author">author</option>
    <option value="catagery">catagery</option>
  </select>
  <input type="submit" value="Go"  class="go";>
</form>
{% if not request.user.is_staff %}
<div class="d-grid gap-2 my-3">
  <a class="btn " style="background-color: rgb(4, 99, 4); color:black" href='{% url "borrowing:add_borrow" %}'> borrow</a>
</div>
{% endif %}
<div class="row">
  {% for bor in borrow %}
  <div class="col-md-3 m-2">
    <div class="card" style="
    background-color: rgb(0, 0, 0);
     color: rgb(255, 255, 255);
     text-align: center;
     font-family: 'Courier New', Courier, monospace;
     border-radius: 10%;
"style="width: 18rem;" >
      <div class="card-body">
        <h5 class="card-title">{{bor.user}}</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{bor.book}}</h6>
        <p class="card-text">Expired: {{bor.exp}}</p>
        <a href="{% url 'borrowing:borrowing_detail' bor.id %}" class="card-link btn btn-outline-primary">More
          Detail</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock content %}