accounts/urls.py
from django.urls import path
from .views import profile, profile_edit, signup


app_name = 'accounts'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('profile/', profile, name='profile'),
    path('profile/edit/', profile_edit, name='profile_edit'),
]

borrowing/urls.py
from django.urls import path
from . import views


app_name = 'borrowing'


urlpatterns = [
    path('', views.borrowing_list, name='borrowing_list'),
    path('add/', views.add_borrow, name='add_borrow'),
    path('<borrow_id>/', views.borrowing_detail, name='borrowing_detail'),
    path('<borrow_id>/edit/', views.edit_borrow, name='edit_borrow'),
    path('<borrow_id>/delete/', views.delete_borrow, name='delete_borrow'),
]

lib/urls.py
from django.urls import path
from . import views


app_name = 'lib'


urlpatterns = [
    path('', views.BookList.as_view(), name='book_list'),
    path('<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
    path('add/', views.add_book, name='add_book'),
    path('<book_id>/edit/', views.edit_book, name='edit_book'),
    path('<book_id>/delete/', views.delete_book, name='delete_book'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),

    path('', include('lib.urls', namespace='lib')),
    path('borrowing/', include('borrowing.urls', namespace='borrowing')),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  {% load static %}
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Library</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
    body
    {
    background-image: url("{%static 'image/library4.jpg' %}");
    background-size:cover;
    background-position: center;
    background-attachment: fixed;
    }
    .logo
    {
      height: 50px;
      width: 50px;
    }
    .logo:hover {
  transform: scaleX(-1);
}

      </style>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light" >
    <div class="container">
      <img src="{%static 'image/logo.png' %}"  class="logo">
      <a class="navbar-brand" href="{% url 'lib:book_list' %}">Goleador Library</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link" href="{% url 'lib:book_list' %}">Home</a>
          {% if not request.user.is_staff %}
          <a class="nav-link" href="{% url 'borrowing:borrowing_list' %}">Borrowings</a>
          {% endif %}
        </div>
        
        <div class="navbar-nav ms-auto">
          {% if request.user.is_authenticated %}
          <a class="nav-link" href="{% url 'accounts:profile' %}">profile</a>
          <a class="nav-link btn " style="background-color: rgb(245, 194, 56);" href="{% url 'logout' %}">Logout</a>
          {% else %}
          <a class="nav-link" aria-current="page" href="{% url 'login' %}">Login</a>
          <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>
  <main class="container mt-5">
    {% block content %}

    {% endblock content %}
  </main>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
    integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
    crossorigin="anonymous"></script>
</body>

</html>