lib/urls.py
from django.urls import path
from . import views


app_name = 'lib'


urlpatterns = [
    path('', views.BookList.as_view(), name='book_list'),
    path('<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
    path('add/', views.add_book, name='add_book'),
    path('<book_id>/edit/', views.edit_book, name='edit_book'),
    path('<book_id>/delete/', views.delete_book, name='delete_book'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),

    path('', include('lib.urls', namespace='lib')),
    path('borrowing/', include('borrowing.urls', namespace='borrowing')),

]

lib/models.py
from django.db import models


class Book(models.Model):
    name = models.CharField(max_length=100)
    isbn = models.PositiveIntegerField()
    author = models.ForeignKey(
        'Author', related_name='author_book', on_delete=models.CASCADE)
    category = models.ForeignKey(
        'Category', related_name='category_book', on_delete=models.CASCADE)
    borrowed = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.name} - {self.isbn}"


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return str(self.name)


class Author(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return str(self.name)

lib/forms.py
from django import forms
from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = "__all__"

lib/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from .models import Book, Category, Author
from .forms import BookForm
from django.db.models import Count, Q


class BookList(ListView):
    model = Book

    def get_queryset(self):
        object_list = Book.objects.filter(borrowed=False)
        return object_list


class BookDetail(DetailView):
    model = Book

    def get_queryset(self):
        book = Book.objects.filter(borrowed=False)
        return book


def add_book(request):
    if request.user.is_authenticated and request.user.is_staff:
        if request.method == 'POST':
            form = BookForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect("lib:book_list")
        else:
            form = BookForm()

        context = {
            "form": form
        }

        return render(request, 'lib/book_add.html', context)
    else:
        return redirect('login')


def edit_book(request, book_id):
    if request.user.is_authenticated and request.user.is_staff:
        book = get_object_or_404(Book, pk=book_id)
        if request.method == 'POST':
            form = BookForm(request.POST, instance=book)
            if form.is_valid():
                form.save()
                return redirect("lib:book_list")
        else:
            form = BookForm(instance=book)

        context = {
            "form": form
        }

        return render(request, 'lib/book_add.html', context)
    else:
        return redirect('login')


def delete_book(request, book_id):
    if request.user.is_authenticated and request.user.is_staff:
        book = get_object_or_404(Book, pk=book_id)
        book.delete()
        return redirect("lib:book_list")
    else:
        return redirect('login')

lib/templates/lib/book_add.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<style>
  .col-md-6
  {
    background-color: rgb(98, 99, 99);
  }
  </style>
<div class="row">
  <div class="col-md-6 mx-auto ">
    <form method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <div class="d-grid gap-2 my-3">
        <input type="submit" value="add / edit book" class="btn btn-success">
      </div>
    </form>
  </div>
</div>
{% endblock content %}

lib/templates/lib/book_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="txt" style="color: chocolate; background-color: rgba(73, 73, 73, 0.9);" >
<h1 style="color: rgb(240, 240, 240);">Name: {{book.name}}</h1>
<h2 style="color: rgb(233, 233, 233);">ISBN: {{book.isbn}}</h2>
<p style="color: rgb(238, 238, 238);"> Author: {{book.author}}</p>
<p style="color: rgb(247, 247, 247);">Category: {{book.category}}</p>
</div>
{% if request.user.is_staff %}
<a href="{% url 'lib:edit_book' book.id %}" class="btn" style="background-color: rgb(228, 187, 5); color:black">edit</a>
<a href="{% url 'lib:delete_book' book.id %}" class="btn" style="background-color: rgb(211, 14, 8); color:black">delete</a>
{% endif %}

{% endblock content %}

lib/templates/lib/book_list.html
{% extends 'base.html' %}

{% block content %}
<style>
   .d
  {
    background-color: rgb(71, 71, 71);
  }
  .go
  {
    background-color: rgb(0, 0, 0);
    width: 90px;
    border-radius: 8%;
    color: cornsilk;
  }
  </style>
<form action="" class="d" method="POST">
  {% csrf_token %}
  <label style="color :bisque">search</label>
  <input type="search" name="search">
  <select name="select" id="se" >
    <option value="name">name</option>
    <option value="isbn">isbn</option>
    <option value="author">author</option>
    <option value="catagery">catagery</option>
  </select>
  <input type="submit" value="Go"  class="go";>
</form>


{% if request.user.is_staff %}
<div class="d-grid gap-2 my-3">
  <a class="btn" style="background-color: rgb(4, 99, 4); color:black" href='{% url "lib:add_book" %}'>add book</a>
</div>
{% endif %}
<div class="row">
  {% for book in object_list %}
  <div class="col-md-3 m-2">
    <div style="
        background-color: rgb(0, 0, 0);
         color: rgb(255, 255, 255);
         text-align: center;
         font-family: 'Courier New', Courier, monospace;
         border-radius: 10%;
    "
     class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title" style="color: chocolate;">{{book.name}}</h5>
        <h6 class="card-subtitle mb-2 text-muted" style="font-weight: bolder;" style="color: chocolate;">{{book.isbn}}</h6>
        <p class="card-text" style="color: chocolate;" >author: {{book.author}}</p>
        <p class="card-text" style="color: chocolate;">category: {{book.category}}</p>
        <a href="{% url 'lib:book_detail' book.id %}" class="card-link btn btn-outline-primary">More
          Detail</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock content %}